#! /usr/local/bin/node

var exec = require('child_process').execSync;
var lambda = require('aws-sdk').Lambda;
var readFile = require('fs').readFileSync;

exec('zip -r module.zip index.js renderer.js serializer.js node_modules');

var config = { region: 'us-east-1' };

var params = {
  FunctionName: 'slack-mtg-card-fetcher',
  Publish: true,
  ZipFile: readFile('module.zip')
};

function callback(err, data) {
  console.log(err ? ['Error', err, err.stack] : ['Success', data]);
}

new lambda(config).updateFunctionCode(params, callback);